spring.application.name=portfolio-backend

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://ghuleyogesh856_db_user:ol7rtz6jxWAH5wD1@cluster0.r211d4g.mongodb.net/portfolio_db?retryWrites=true&w=majority&appName=Cluster0}

server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always